[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.26"

[programs.localnet]
univerz_solana_backend = "3uqqbb6uzsy5koJgsJqKR86tmNLNBLp3d7HtozHi4LZh"

[provider]
# Configured to localnet so tests execute locally and for free
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha tests/univerz-arena.ts --timeout 1000000"

[hooks]

[test.validator]
bind_address = "127.0.0.1"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899